### ISSUE TITLE
Is this works on python 2.7?

### ISSUE THREAD

**Issue by kjur** [mozilla/moz_crlite_query#17]
I've installed this for python 2.7 and I got following error:
```
$ moz_crlite_query 
Traceback (most recent call last):
  File "/usr/local/bin/moz_crlite_query", line 5, in <module>
    from crlite_query.query_cli import main
  File "/usr/local/lib/python2.7/site-packages/crlite_query/__init__.py", line 26
    def ensure_local(*, base_url, entry, local_path):
                      ^
SyntaxError: invalid syntax
```

Is this works on python 2.7? Is this requires python3 or later?

**Comment by jcjones** [comment]
The setup.py defines a minimum version of Python 3.7; older Setuptools doesn't understand the minimum version field, sadly.

**Comment by jcjones** [comment]
Actually, let's make sure that's up front in the README.
